repeat last yaw and pitch if line section is '*'
HLTAS/hltas pull request #2
Opened 2018-04-30 13:42 UTC by philippTheCat

2018-04-30 14:20 UTC, YaLTeR commented
Eh I dunno about this tbh.

2018-04-30 14:22 UTC, YaLTeR commented
Although I suppose it can be helpful. Do you have any other suggestions for the actual character? Not sure `*` is the best fit here.

EDIT: how about `_` which is used in some languages as a placeholder.

2018-04-30 14:26 UTC, YaLTeR requested changes
Here's a review.

2018-04-30 14:26 UTC, YaLTeR commented on src/hltas.cpp
> +
Extra blank line

2018-04-30 14:26 UTC, YaLTeR commented on src/hltas.cpp
> +		float lastYaw = 0, lastPitch = 0;
`lastYaw` should be `double`.

2018-04-30 14:26 UTC, YaLTeR commented on src/hltas.cpp
> +					if (!std::isdigit(str[0]) && (str[0] != '-' && str[0] != '*'))
Extra `()` not needed.

2018-04-30 14:26 UTC, YaLTeR commented on src/hltas.cpp
> +						f.Yaw = lastYaw;
Well, what happens if there's no last yaw? That's right, undefined behavior, which is bad. Make `lastYaw` a `std::optional` and make it an error if it's not present.

2018-04-30 14:26 UTC, YaLTeR commented on src/hltas.cpp
> +							try {
You messed up the indentation on this block up until `break;`. It should be one level to the left.

2018-04-30 14:26 UTC, YaLTeR commented on src/hltas.cpp
> +					if (!std::isdigit(str[0]) && (str[0] != '-' && str[0] != '*'))
Extra `()` not needed.

2018-04-30 14:26 UTC, YaLTeR commented on src/hltas.cpp
> +						f.Pitch = lastPitch;
Same thing about undefined behaviour.

2018-04-30 14:26 UTC, YaLTeR commented on src/hltas.cpp
> +					else {
Should be on the previous line.

2018-04-30 14:26 UTC, YaLTeR commented on src/hltas.cpp
> +
Extra blank line.

2018-04-30 14:26 UTC, YaLTeR commented on src/hltas.cpp
> +						catch (boost::bad_lexical_cast) {
Should be on the previous line.

2018-04-30 14:26 UTC, YaLTeR commented on src/hltas.cpp
> +				break;
Should be one indentation to the right.

2018-04-30 14:35 UTC, Matherunner commented
Maybe the ^ character?

2018-04-30 14:47 UTC, YaLTeR commented
Hm that could work yeah

2019-12-26 14:59 UTC, YaLTeR commented
This PR is now stale as hltas was rewritten from scratch.

2019-12-26 14:59 UTC, closed without merging